Rails:
  Enabled: true
AllCops:
  Include:
    - Rakefile
    - config.ru
    - lib/**/*.rake
  Exclude:
    - db/schema.rb
    - bin/spring*
Style/Documentation:
  Enabled: false
Metrics/MethodLength:
  Exclude:
    - db/migrate/20160924131227_devise_create_users.rb
Metrics/LineLength:
  Exclude:
    - config/initializers/simple_form.rb
    - config/initializers/simple_form_bootstrap.rb
